apiVersion: v1
kind: Pod
metadata:
  annotations:
    debug.openshift.io/source-container: debug
    debug.openshift.io/source-resource: /v1, Resource=pods/image
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.128.0.71/23"],"mac_address":"0a:58:0a:80:00:47","gateway_ips":["10.128.0.1"],"routes":[{"dest":"10.128.0.0/14","nextHop":"10.128.0.1"},{"dest":"172.30.0.0/16","nextHop":"10.128.0.1"},{"dest":"100.64.0.0/16","nextHop":"10.128.0.1"}],"ip_address":"10.128.0.71/23","gateway_ip":"10.128.0.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.0.71"
          ],
          "mac": "0a:58:0a:80:00:47",
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: anyuid
  name: dpll-debug
  namespace: openshift-ptp
  resourceVersion: "5743157"
spec:
  containers:
  - command:
    - /bin/sh
    image: quay.io/redhat-partner-solutions/dpll-debug:0.2
    imagePullPolicy: Always
    name: debug
    resources: {}
    securityContext:
        privileged: true
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
            #- name: kmodules
            #mountPath: /lib/modules
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-75xgz
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: default-dockercfg-wkkdm
    #nodeName: r740-u27.cormorant.wpc.test
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  volumes:
          #- name: kmodules
          #hostPath:
          #path: /lib/modules
          #type: Directory
  - name: kube-api-access-75xgz
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
